//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("oss-tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@achievementify/client&quot;,&quot;_rev&quot;:&quot;12-8838c4a3d8562d02f2daef2375606cf6&quot;,&quot;time&quot;:{&quot;created&quot;:&quot;2022-06-04T14:02:08.273Z&quot;,&quot;0.1.0&quot;:&quot;2022-06-04T13:57:49.506Z&quot;,&quot;modified&quot;:&quot;2022-06-07T01:29:39.806Z&quot;,&quot;0.1.1&quot;:&quot;2022-06-04T14:02:08.514Z&quot;,&quot;0.1.2&quot;:&quot;2022-06-04T14:05:49.363Z&quot;,&quot;0.1.3&quot;:&quot;2022-06-04T14:22:29.219Z&quot;,&quot;0.2.0&quot;:&quot;2022-06-05T13:10:17.513Z&quot;,&quot;0.2.1&quot;:&quot;2022-06-07T01:17:09.495Z&quot;,&quot;0.2.3&quot;:&quot;2022-06-07T01:29:39.737Z&quot;},&quot;name&quot;:&quot;@achievementify/client&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.2.3&quot;},&quot;versions&quot;:{&quot;0.1.1&quot;:{&quot;name&quot;:&quot;@achievementif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string achievementify_client_json {
            get {
                return ResourceManager.GetString("achievementify_client.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@angular/core&quot;,&quot;_rev&quot;:&quot;660-3fe4d5b1b9e632c7d96cdc1e1005b13c&quot;,&quot;name&quot;:&quot;@angular/core&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;13.2.6&quot;,&quot;v4-lts&quot;:&quot;4.4.7&quot;,&quot;v5-lts&quot;:&quot;5.2.11&quot;,&quot;next&quot;:&quot;13.3.0-rc.0&quot;,&quot;v7-lts&quot;:&quot;7.2.15&quot;,&quot;v6-lts&quot;:&quot;6.1.10&quot;,&quot;v9-lts&quot;:&quot;9.1.13&quot;,&quot;v8-lts&quot;:&quot;8.2.14&quot;,&quot;v10-lts&quot;:&quot;10.2.5&quot;,&quot;v11-lts&quot;:&quot;11.2.14&quot;,&quot;v12-lts&quot;:&quot;12.2.16&quot;},&quot;versions&quot;:{&quot;0.0.0-0&quot;:{&quot;name&quot;:&quot;@angular/core&quot;,&quot;version&quot;:&quot;0.0.0-0&quot;,&quot;description&quot;:&quot;&quot;,&quot;main&quot;:&quot;index.js&quot;,&quot;jsnext:main&quot;:&quot;esm/index.js&quot;,&quot;typings&quot;:&quot;index.d.ts&quot;,&quot;author&quot;:{&quot;name&quot;:&quot;angular&quot;},&quot;license&quot;:&quot;MIT&quot;,&quot;pee [rest of string was tru....
        /// </summary>
        internal static string angular_core_json {
            get {
                return ResourceManager.GetString("angular_core.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;rand&quot;,&quot;vers&quot;:&quot;0.1.1&quot;,&quot;deps&quot;:[],&quot;cksum&quot;:&quot;48a45b46c2a8c38348adb1205b13c3c5eb0174e0c0fec52cc88e9fb1de14c54d&quot;,&quot;features&quot;:{},&quot;yanked&quot;:false}
        ///{&quot;name&quot;:&quot;rand&quot;,&quot;vers&quot;:&quot;0.1.2&quot;,&quot;deps&quot;:[{&quot;name&quot;:&quot;libc&quot;,&quot;req&quot;:&quot;^0.1.1&quot;,&quot;features&quot;:[&quot;&quot;],&quot;optional&quot;:false,&quot;default_features&quot;:true,&quot;target&quot;:null,&quot;kind&quot;:&quot;normal&quot;},{&quot;name&quot;:&quot;log&quot;,&quot;req&quot;:&quot;^0.2.1&quot;,&quot;features&quot;:[&quot;&quot;],&quot;optional&quot;:false,&quot;default_features&quot;:true,&quot;target&quot;:null,&quot;kind&quot;:&quot;normal&quot;}],&quot;cksum&quot;:&quot;6e229ed392842fa93c1d76018d197b7e1b74250532bafb37b0e1d121a92d4cf7&quot;,&quot;features&quot;:{},&quot;ya [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cargo_rand {
            get {
                return ResourceManager.GetString("cargo.rand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;categories&quot;: [
        ///    {
        ///      &quot;category&quot;: &quot;Algorithms&quot;,
        ///      &quot;crates_cnt&quot;: 1905,
        ///      &quot;created_at&quot;: &quot;2017-01-17T19:13:05.112025+00:00&quot;,
        ///      &quot;description&quot;: &quot;Rust implementations of core algorithms such as hashing, sorting, searching, and more.&quot;,
        ///      &quot;id&quot;: &quot;algorithms&quot;,
        ///      &quot;slug&quot;: &quot;algorithms&quot;
        ///    },
        ///    {
        ///      &quot;category&quot;: &quot;No standard library&quot;,
        ///      &quot;crates_cnt&quot;: 4518,
        ///      &quot;created_at&quot;: &quot;2017-02-10T01:52:09.447906+00:00&quot;,
        ///      &quot;description&quot;: &quot;Crates that are able to function wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cargo_rand_json {
            get {
                return ResourceManager.GetString("cargo.rand.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;ds-modal&quot;,&quot;_rev&quot;:&quot;9-9ea35761f56735940a8303bde2186667&quot;,&quot;time&quot;:{&quot;1.0.0&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.1&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.2&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.3&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.4&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;created&quot;:&quot;2018-08-06T12:04:34.792Z&quot;,&quot;0.0.0&quot;:&quot;2018-08-06T12:04:34.910Z&quot;,&quot;modified&quot;:&quot;2018-08-09T07:24:09.131Z&quot;,&quot;0.0.1&quot;:&quot;2018-08-09T04:53:46.623Z&quot;,&quot;0.0.2&quot;:&quot;2018-08-09T07:24:06.206Z&quot;},&quot;name&quot;:&quot;ds-modal&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.2&quot;},&quot;versions&quot;:{&quot;0.0.0&quot;:{&quot;name&quot;:&quot;ds-modal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ds_modal_json {
            get {
                return ResourceManager.GetString("ds-modal.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:&quot;v1.3.0&quot;,&quot;Time&quot;:&quot;2021-09-22T21:48:32Z&quot;}.
        /// </summary>
        internal static string go_yaml_1_3_0_info {
            get {
                return ResourceManager.GetString("go_yaml_1.3.0_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module sigs.k8s.io/yaml
        ///
        ///go 1.12
        ///
        ///require (
        ///	github.com/davecgh/go-spew v1.1.1
        ///	gopkg.in/yaml.v2 v2.4.0
        ///).
        /// </summary>
        internal static string go_yaml_1_3_0_mod {
            get {
                return ResourceManager.GetString("go_yaml_1.3.0_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.3.0
        ///v1.0.0
        ///v1.2.0
        ///v1.1.0.
        /// </summary>
        internal static string go_yaml_list {
            get {
                return ResourceManager.GetString("go_yaml_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;lodash&quot;,&quot;_rev&quot;:&quot;2650-7b310ba0ce49a17115204773ce251b7f&quot;,&quot;name&quot;:&quot;lodash&quot;,&quot;description&quot;:&quot;Lodash modular utilities.&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;4.17.21&quot;},&quot;versions&quot;:{&quot;0.1.0&quot;:{&quot;name&quot;:&quot;lodash&quot;,&quot;version&quot;:&quot;0.1.0&quot;,&quot;description&quot;:&quot;A drop-in replacement for Underscore.js that delivers up to 8x performance improvements, bug fixes, and additional features.&quot;,&quot;homepage&quot;:&quot;https://github.com/bestiejs/lodash&quot;,&quot;main&quot;:&quot;lodash&quot;,&quot;keywords&quot;:[&quot;browser&quot;,&quot;client&quot;,&quot;functional&quot;,&quot;performance&quot;,&quot;server&quot;,&quot;speed&quot;,&quot;util&quot;],&quot;licenses&quot;:[{&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lodash_json {
            get {
                return ResourceManager.GetString("lodash.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;lodash.js&quot;,&quot;_rev&quot;:&quot;7-b033eedf4d1b14d686a8c537585bb116&quot;,&quot;time&quot;:{&quot;4.17.16&quot;:&quot;2019-11-25T16:45:29.666Z&quot;,&quot;created&quot;:&quot;2019-11-25T18:50:27.244Z&quot;,&quot;0.0.1-security&quot;:&quot;2019-11-25T18:50:27.445Z&quot;,&quot;modified&quot;:&quot;2022-05-08T08:11:30.890Z&quot;},&quot;name&quot;:&quot;lodash.js&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.1-security&quot;},&quot;versions&quot;:{&quot;0.0.1-security&quot;:{&quot;name&quot;:&quot;lodash.js&quot;,&quot;version&quot;:&quot;0.0.1-security&quot;,&quot;description&quot;:&quot;security holding package&quot;,&quot;repository&quot;:{&quot;type&quot;:&quot;git&quot;,&quot;url&quot;:&quot;git+https://github.com/npm/security-holder.git&quot;},&quot;gitHead&quot;:&quot;ac50be87aafecb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lodashjs_json {
            get {
                return ResourceManager.GetString("lodashjs.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;Central Repository: ant/ant/1.6&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;style&gt;
        ///body {
        ///	background: #fff;
        ///}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	&lt;header&gt;
        ///		&lt;h1&gt;ant/ant/1.6&lt;/h1&gt;
        ///	&lt;/header&gt;
        ///	&lt;hr/&gt;
        ///	&lt;main&gt;
        ///		&lt;pre id=&quot;contents&quot;&gt;
        ///&lt;a href=&quot;../&quot;&gt;../&lt;/a&gt;
        ///&lt;a href=&quot;ant-1.6-sources.jar&quot; title=&quot;ant-1.6-sources.jar&quot;&gt;ant-1.6-sources.jar&lt;/a&gt;                               2005-09-20 05:44   2182693      
        ///&lt;a href=&quot;ant-1.6-sources.jar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_ant_1_6_html {
            get {
                return ResourceManager.GetString("maven_ant_1.6_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project&gt;
        ///    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
        ///    &lt;groupId&gt;ant&lt;/groupId&gt;
        ///    &lt;artifactId&gt;ant&lt;/artifactId&gt;
        ///    &lt;name&gt;Ant&lt;/name&gt;
        ///    &lt;version&gt;1.6&lt;/version&gt;
        ///&lt;/project&gt;.
        /// </summary>
        internal static string maven_ant_1_6_pom {
            get {
                return ResourceManager.GetString("maven_ant_1.6_pom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;Central Repository: ant/ant&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;style&gt;
        ///body {
        ///	background: #fff;
        ///}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	&lt;header&gt;
        ///		&lt;h1&gt;ant/ant&lt;/h1&gt;
        ///	&lt;/header&gt;
        ///	&lt;hr/&gt;
        ///	&lt;main&gt;
        ///		&lt;pre id=&quot;contents&quot;&gt;
        ///&lt;a href=&quot;../&quot;&gt;../&lt;/a&gt;
        ///&lt;a href=&quot;1.4.1/&quot; title=&quot;1.4.1/&quot;&gt;1.4.1/&lt;/a&gt;                                            2005-09-20 05:44         -      
        ///&lt;a href=&quot;1.5/&quot; title=&quot;1.5/&quot;&gt;1.5/&lt;/a&gt;                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_ant_all_html {
            get {
                return ResourceManager.GetString("maven_ant_all_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;metadata&gt;
        ///    &lt;groupId&gt;ant&lt;/groupId&gt;
        ///    &lt;artifactId&gt;ant&lt;/artifactId&gt;
        ///    &lt;version&gt;1.4.1&lt;/version&gt;
        ///    &lt;versioning&gt;
        ///        &lt;versions&gt;
        ///            &lt;version&gt;1.4.1&lt;/version&gt;
        ///            &lt;version&gt;1.5&lt;/version&gt;
        ///            &lt;version&gt;1.5.1&lt;/version&gt;
        ///            &lt;version&gt;1.5.2&lt;/version&gt;
        ///            &lt;version&gt;1.5.3-1&lt;/version&gt;
        ///            &lt;version&gt;1.5.4&lt;/version&gt;
        ///            &lt;version&gt;1.6&lt;/version&gt;
        ///            &lt;version&gt;1.6.1&lt;/version&gt;
        ///            &lt;version&gt;1.6.2&lt;/version&gt;
        ///            &lt;version&gt;1.6.3&lt;/ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_ant_metadata_xml {
            get {
                return ResourceManager.GetString("maven_ant_metadata_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot; xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
        ///  &lt;groupId&gt;com.microsoft.fluentui&lt;/groupId&gt;
        ///  &lt;artifactId&gt;fluentui_listitem&lt;/artifactId&gt;
        ///  &lt;version&gt;0.0.8&lt;/version&gt;
        ///  &lt;packaging&gt;aar&lt;/packaging&gt;
        ///  &lt;name&gt;fluentui_listitem&lt;/name&gt;
        ///  &lt;description&gt;Fluent UI Android, Module : fluentui_l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_fluentui_listitem_0_0_8_pom {
            get {
                return ResourceManager.GetString("maven_fluentui_listitem_0.0.8_pom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0078)https://repo1.maven.org/maven2/com/microsoft/fluentui/fluentui_listitem/0.0.8/ --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///	&lt;title&gt;Central Repository: com/microsoft/fluentui/fluentui_listitem/0.0.8&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;style&gt;
        ///body {
        ///	background: #fff;
        ///}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	&lt;header&gt;
        ///		&lt;h1&gt;com/microsoft/fluentui/fluentui_listitem/0.0.8&lt;/h1&gt;
        ///	&lt;/header&gt;
        ///	&lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_microsoft_fluentui_listitem_0_0_8_html {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_0.0.8_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0072)https://repo1.maven.org/maven2/com/microsoft/fluentui/fluentui_listitem/ --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///	&lt;title&gt;Central Repository: com/microsoft/fluentui/fluentui_listitem&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;style&gt;
        ///body {
        ///	background: #fff;
        ///}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	&lt;header&gt;
        ///		&lt;h1&gt;com/microsoft/fluentui/fluentui_listitem&lt;/h1&gt;
        ///	&lt;/header&gt;
        ///	&lt;hr&gt;
        ///	&lt;main&gt;
        ///		&lt;pre  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_microsoft_fluentui_listitem_all_html {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_all_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;metadata&gt;
        ///  &lt;groupId&gt;com.microsoft.fluentui&lt;/groupId&gt;
        ///  &lt;artifactId&gt;fluentui_listitem&lt;/artifactId&gt;
        ///  &lt;versioning&gt;
        ///    &lt;latest&gt;0.1.6&lt;/latest&gt;
        ///    &lt;release&gt;0.1.6&lt;/release&gt;
        ///    &lt;versions&gt;
        ///      &lt;version&gt;0.0.24&lt;/version&gt;
        ///      &lt;version&gt;0.1.0&lt;/version&gt;
        ///      &lt;version&gt;0.1.1&lt;/version&gt;
        ///      &lt;version&gt;0.1.2&lt;/version&gt;
        ///      &lt;version&gt;0.1.3&lt;/version&gt;
        ///      &lt;version&gt;0.1.4&lt;/version&gt;
        ///      &lt;version&gt;0.1.5&lt;/version&gt;
        ///      &lt;version&gt;0.1.6&lt;/version&gt;
        ///    &lt;/versions&gt;
        ///    &lt;lastUpdated&gt;20230 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maven_microsoft_fluentui_listitem_metadata_xml {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_metadata_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;example&quot;,&quot;name&quot;:&quot;example&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.0&quot;},&quot;versions&quot;:{&quot;0.0.0&quot;:{&quot;name&quot;:&quot;example&quot;,&quot;version&quot;:&quot;0.0.0&quot;,&quot;_id&quot;:&quot;example@0.0.0&quot;,&quot;_npmVersion&quot;:&quot;1.0.0&quot;,&quot;_npmUser&quot;:{&quot;name&quot;:&quot;test&quot;,&quot;email&quot;:&quot;test@microsoft.com&quot;}}},&quot;time&quot;:{&quot;created&quot;:&quot;2022-08-10T21:35:37.950Z&quot;,&quot;0.0.0&quot;:&quot;2022-08-10T21:35:38.278Z&quot;,&quot;modified&quot;:&quot;2022-08-10T21:35:37.950Z&quot;}}.
        /// </summary>
        internal static string minimum_json_json {
            get {
                return ResourceManager.GetString("minimum_json.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;monorepolint&quot;,&quot;_rev&quot;:&quot;87-5da61e286f7f5e22c777a521cea5ef96&quot;,&quot;name&quot;:&quot;monorepolint&quot;,&quot;dist-tags&quot;:{&quot;canary&quot;:&quot;0.5.0-alpha.81&quot;,&quot;latest&quot;:&quot;0.4.0&quot;},&quot;versions&quot;:{&quot;0.2.1-alpha.0&quot;:{&quot;name&quot;:&quot;monorepolint&quot;,&quot;version&quot;:&quot;0.2.1-alpha.0&quot;,&quot;license&quot;:&quot;MIT&quot;,&quot;scripts&quot;:{&quot;clean&quot;:&quot;rm -rf build lib&quot;,&quot;compile:typescript&quot;:&quot;../../node_modules/.bin/tsc&quot;,&quot;jest:watch&quot;:&quot;../../node_modules/.bin/jest --config ../../jest.config.js --watch&quot;,&quot;jest&quot;:&quot;../../node_modules/.bin/jest --config ../../jest.config.js&quot;,&quot;lint:typescript&quot;:&quot;../../node_modu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monorepolint_json {
            get {
                return ResourceManager.GetString("monorepolint.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:&quot;3.0.0&quot;,&quot;resources&quot;:[{&quot;@id&quot;:&quot;https://azuresearch-usnc.nuget.org/query&quot;,&quot;@type&quot;:&quot;SearchQueryService&quot;,&quot;comment&quot;:&quot;Query endpoint of NuGet Search service (primary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-ussc.nuget.org/query&quot;,&quot;@type&quot;:&quot;SearchQueryService&quot;,&quot;comment&quot;:&quot;Query endpoint of NuGet Search service (secondary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-usnc.nuget.org/autocomplete&quot;,&quot;@type&quot;:&quot;SearchAutocompleteService&quot;,&quot;comment&quot;:&quot;Autocomplete endpoint of NuGet Search service (primary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-ussc.n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nuget_registration_json {
            get {
                return ResourceManager.GetString("nuget_registration.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;The Pandas Development Team&quot;,&quot;author_email&quot;:&quot;pandas-dev@python.org&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Environment :: Console&quot;,&quot;Intended Audience :: Science/Research&quot;,&quot;License :: OSI Approved :: BSD License&quot;,&quot;Operating System :: OS Independent&quot;,&quot;Programming Language :: Cython&quot;,&quot;Programming Language :: Python&quot;,&quot;Programming Language :: Python :: 3&quot;,&quot;Programming Language :: Python :: 3 :: Only&quot;,&quot;Programming Language :: Python :: 3.10&quot;,&quot;Programmi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pandas_1_4_2_json {
            get {
                return ResourceManager.GetString("pandas_1.4.2.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;The Pandas Development Team&quot;,&quot;author_email&quot;:&quot;pandas-dev@python.org&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Environment :: Console&quot;,&quot;Intended Audience :: Science/Research&quot;,&quot;License :: OSI Approved :: BSD License&quot;,&quot;Operating System :: OS Independent&quot;,&quot;Programming Language :: Cython&quot;,&quot;Programming Language :: Python&quot;,&quot;Programming Language :: Python :: 3&quot;,&quot;Programming Language :: Python :: 3 :: Only&quot;,&quot;Programming Language :: Python :: 3.8&quot;,&quot;Programmin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pandas_json {
            get {
                return ResourceManager.GetString("pandas.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;Chris P&quot;,&quot;author_email&quot;:&quot;chris@plot.ly&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Programming Language :: Python :: 3.6&quot;,&quot;Programming Language :: Python :: 3.7&quot;,&quot;Programming Language :: Python :: 3.8&quot;,&quot;Programming Language :: Python :: 3.9&quot;,&quot;Topic :: Scientific/Engineering :: Visualization&quot;],&quot;description&quot;:&quot;# plotly.py\n\n&lt;table&gt;\n    &lt;tr&gt;\n        &lt;td&gt;Latest Release&lt;/td&gt;\n        &lt;td&gt;\n            &lt;a href=\&quot;https://pypi.org/project/plotly/\&quot;/&gt;\n     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plotly_5_7_0_json {
            get {
                return ResourceManager.GetString("plotly_5.7.0.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;Chris P&quot;,&quot;author_email&quot;:&quot;chris@plot.ly&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Programming Language :: Python :: 3.6&quot;,&quot;Programming Language :: Python :: 3.7&quot;,&quot;Programming Language :: Python :: 3.8&quot;,&quot;Programming Language :: Python :: 3.9&quot;,&quot;Topic :: Scientific/Engineering :: Visualization&quot;],&quot;description&quot;:&quot;# plotly.py\n\n&lt;table&gt;\n    &lt;tr&gt;\n        &lt;td&gt;Latest Release&lt;/td&gt;\n        &lt;td&gt;\n            &lt;a href=\&quot;https://pypi.org/project/plotly/\&quot;/&gt;\n     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plotly_json {
            get {
                return ResourceManager.GetString("plotly.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2022.03.11.23.17.27/razorengine.4.2.3-beta1.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;c6bb0713-e534-4b16-8fdc-e199a77a6d73&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2022-03-11T23:17:27.9312336Z&quot;,
        ///  &quot;copyright&quot;: &quot;Copyright 2015&quot;,
        ///  &quot;created&quot;: &quot;2015-10-06T17:53:46.37Z&quot;,
        ///  &quot;description&quot;: &quot;RazorEngine - A Templating Engine based on the Razor parser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_4_2_3_beta1_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;authors&quot;:&quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,&quot;dependencyGroups&quot;:[{&quot;TargetFramework&quot;:{&quot;Framework&quot;:&quot;Any&quot;,&quot;Version&quot;:&quot;0.0.0.0&quot;,&quot;Platform&quot;:&quot;&quot;,&quot;PlatformVersion&quot;:&quot;0.0.0.0&quot;,&quot;HasPlatform&quot;:false,&quot;HasProfile&quot;:false,&quot;Profile&quot;:&quot;&quot;,&quot;DotNetFrameworkName&quot;:&quot;Any,Version=v0.0&quot;,&quot;DotNetPlatformName&quot;:&quot;&quot;,&quot;IsPCL&quot;:false,&quot;IsPackageBased&quot;:false,&quot;AllFrameworkVersions&quot;:true,&quot;IsUnsupported&quot;:false,&quot;IsAgnostic&quot;:false,&quot;IsAny&quot;:true,&quot;IsSpecificFramework&quot;:false},&quot;Packages&quot;:[{&quot;Id&quot;:&quot;Microsoft.AspNet.Razor&quot;,&quot;Include&quot;:[],&quot;Exclude&quot;:[] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_4_2_3_beta1_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.metadata.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/razorengine/index.json&quot;,&quot;@type&quot;:[&quot;catalog:CatalogRoot&quot;,&quot;PackageRegistration&quot;,&quot;catalog:Permalink&quot;],&quot;commitId&quot;:&quot;b44e2827-f5db-4ba2-bb8c-5e538ad0e7b1&quot;,&quot;commitTimeStamp&quot;:&quot;2022-03-11T23:18:21.9196828+00:00&quot;,&quot;count&quot;:2,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/razorengine/index.json#page/2.1.0/4.1.5-beta1&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;b44e2827-f5db-4ba2-bb8c-5e538ad0e7b1&quot;,&quot;commitTimeStamp&quot;:&quot;2022-03-11T23:18:21.9196828+0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_json {
            get {
                return ResourceManager.GetString("razorengine.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;authors&quot;: &quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,
        ///  &quot;dependencyGroups&quot;: [
        ///    {
        ///      &quot;TargetFramework&quot;: {
        ///        &quot;Framework&quot;: &quot;.NETFramework&quot;,
        ///        &quot;Version&quot;: &quot;4.5.1.0&quot;,
        ///        &quot;Platform&quot;: &quot;&quot;,
        ///        &quot;PlatformVersion&quot;: &quot;0.0.0.0&quot;,
        ///        &quot;HasPlatform&quot;: false,
        ///        &quot;HasProfile&quot;: false,
        ///        &quot;Profile&quot;: &quot;&quot;,
        ///        &quot;DotNetFrameworkName&quot;: &quot;.NETFramework,Version=v4.5.1&quot;,
        ///        &quot;DotNetPlatformName&quot;: &quot;&quot;,
        ///        &quot;IsPCL&quot;: false,
        ///        &quot;IsPackageBased&quot;: false,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_latest_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.latest.metadata.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;2.1.0&quot;,&quot;3.0.0&quot;,&quot;3.0.3&quot;,&quot;3.0.4&quot;,&quot;3.0.5&quot;,&quot;3.0.6&quot;,&quot;3.0.7&quot;,&quot;3.0.8&quot;,&quot;3.1.0&quot;,&quot;3.2.0&quot;,&quot;3.3.0&quot;,&quot;3.4.0&quot;,&quot;3.4.1&quot;,&quot;3.4.2&quot;,&quot;3.5.0-beta1&quot;,&quot;3.5.0-beta2&quot;,&quot;3.5.0-beta3&quot;,&quot;3.5.0&quot;,&quot;3.5.1&quot;,&quot;3.5.2&quot;,&quot;3.5.3&quot;,&quot;3.6.0&quot;,&quot;3.6.1&quot;,&quot;3.6.2&quot;,&quot;3.6.3-beta1&quot;,&quot;3.6.3-beta2&quot;,&quot;3.6.3&quot;,&quot;3.6.4&quot;,&quot;3.6.5-beta1&quot;,&quot;3.6.5&quot;,&quot;3.6.6-beta1&quot;,&quot;3.6.6-beta2&quot;,&quot;3.6.6&quot;,&quot;3.7.0-beta1&quot;,&quot;3.7.0&quot;,&quot;3.7.1-alpha1&quot;,&quot;3.7.2&quot;,&quot;3.7.3&quot;,&quot;3.7.4&quot;,&quot;3.7.5-beta1&quot;,&quot;3.7.5-beta2&quot;,&quot;3.7.5&quot;,&quot;3.7.6&quot;,&quot;3.7.7&quot;,&quot;3.8.0&quot;,&quot;3.8.1&quot;,&quot;3.8.2&quot;,&quot;3.9.0&quot;,&quot;3.9.1&quot;,&quot;3.9.2&quot;,&quot;3.9.3&quot;,&quot;3.10.0&quot;,&quot;3.10....
        /// </summary>
        internal static string razorengine_versions_json {
            get {
                return ResourceManager.GetString("razorengine.versions.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;info&quot;: {
        ///    &quot;author&quot;: &quot;Kenneth Reitz&quot;,
        ///    &quot;author_email&quot;: &quot;me@kennethreitz.org&quot;,
        ///    &quot;bugtrack_url&quot;: null,
        ///    &quot;classifiers&quot;: [
        ///      &quot;Development Status :: 5 - Production/Stable&quot;,
        ///      &quot;Environment :: Web Environment&quot;,
        ///      &quot;Intended Audience :: Developers&quot;,
        ///      &quot;License :: OSI Approved :: Apache Software License&quot;,
        ///      &quot;Natural Language :: English&quot;,
        ///      &quot;Operating System :: OS Independent&quot;,
        ///      &quot;Programming Language :: Python&quot;,
        ///      &quot;Programming Language :: Python :: 2&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string requests_2_27_1_json {
            get {
                return ResourceManager.GetString("requests_2.27.1.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;Kenneth Reitz&quot;,&quot;author_email&quot;:&quot;me@kennethreitz.org&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Environment :: Web Environment&quot;,&quot;Intended Audience :: Developers&quot;,&quot;License :: OSI Approved :: Apache Software License&quot;,&quot;Natural Language :: English&quot;,&quot;Operating System :: OS Independent&quot;,&quot;Programming Language :: Python&quot;,&quot;Programming Language :: Python :: 2&quot;,&quot;Programming Language :: Python :: 2.7&quot;,&quot;Programming Language :: Python :: 3&quot;,&quot;Programming Language :: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string requests_json {
            get {
                return ResourceManager.GetString("requests.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;rly-cli&quot;,&quot;_rev&quot;:&quot;3-25e14d2a4e035503eb10824c39a04e6c&quot;,&quot;name&quot;:&quot;rly-cli&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.4&quot;},&quot;versions&quot;:{&quot;0.0.1&quot;:{&quot;name&quot;:&quot;rly-cli&quot;,&quot;version&quot;:&quot;0.0.1&quot;,&quot;description&quot;:&quot;DFS CLI allows you to setup fungilble SPL tokens and call Rally token programs from the command line.&quot;,&quot;bin&quot;:{&quot;rly-cli&quot;:&quot;lib/cli/src/rly-cli.js&quot;},&quot;keywords&quot;:[],&quot;author&quot;:&quot;&quot;,&quot;scripts&quot;:{&quot;tsc&quot;:&quot;tsc&quot;,&quot;test&quot;:&quot;./node_modules/ts-mocha/bin/ts-mocha -p ./tsconfig.json -t 1000000 -r dotenv/config tests/**/*.ts&quot;},&quot;license&quot;:&quot;ISC&quot;,&quot;publishConfi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rly_cli_json {
            get {
                return ResourceManager.GetString("rly-cli.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2022.06.07.08.44.59/slipeserver.scripting.0.1.0-ci-20220607-083949.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Slipe&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;ebe15ca4-3d58-4ff6-a448-940e5af9fcef&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2022-06-07T08:44:59.8308559Z&quot;,
        ///  &quot;created&quot;: &quot;2022-06-07T08:42:15.957Z&quot;,
        ///  &quot;description&quot;: &quot;Scripting layer C# Server for MTA San Andreas&quot;,
        ///  &quot;iconFile&quot;: &quot;slipe-logo.png&quot;,
        ///  &quot;id&quot;: &quot;SlipeServer.Script [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slipeserver_scripting_0_1_0_ci_20220607_083949_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.0.1.0-ci-20220607-083949.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/page/0.1.0-ci-20220325-215611/0.1.0-ci-20220807-160739.json&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;092a36d4-efb8-4e35-8d96-74a12ed8de57&quot;,&quot;commitTimeStamp&quot;:&quot;2022-08-07T16:12:38.9645281+00:00&quot;,&quot;count&quot;:64,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/0.1.0-ci-20220325-215611.json&quot;,&quot;@type&quot;:&quot;Package&quot;,&quot;commitId&quot;:&quot;f9481809-13c3-43c3-8d0e-d6d35d72663a&quot;,&quot;commitTimeStamp&quot;:&quot;2022-03-25T22:03:10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slipeserver_scripting_catalogpage_2_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.catalogpage.2.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/page/0.1.0-ci-20221013-182634/0.1.0-ci-20221120-180516.json&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;5c5c9ce6-0f54-4364-ac33-a79fb8bcc6d3&quot;,&quot;commitTimeStamp&quot;:&quot;2022-11-20T18:10:52.9301862+00:00&quot;,&quot;count&quot;:42,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/0.1.0-ci-20221013-182634.json&quot;,&quot;@type&quot;:&quot;Package&quot;,&quot;commitId&quot;:&quot;48b86cee-4f37-4ad8-ab95-ae84a6b8e2e2&quot;,&quot;commitTimeStamp&quot;:&quot;2022-10-13T18:33:00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slipeserver_scripting_catalogpage_3_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.catalogpage.3.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/index.json&quot;,&quot;@type&quot;:[&quot;catalog:CatalogRoot&quot;,&quot;PackageRegistration&quot;,&quot;catalog:Permalink&quot;],&quot;commitId&quot;:&quot;5c5c9ce6-0f54-4364-ac33-a79fb8bcc6d3&quot;,&quot;commitTimeStamp&quot;:&quot;2022-11-20T18:10:52.9301862+00:00&quot;,&quot;count&quot;:4,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/slipeserver.scripting/page/0.1.0-ci-20210204-180233/0.1.0-ci-20210826-172946.json&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;8f3408ff-7a72-48f4-a532-cb71483f4a05&quot;,&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slipeserver_scripting_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;0.1.0-ci-20210204-180233&quot;,&quot;0.1.0-ci-20210206-131710&quot;,&quot;0.1.0-ci-20210206-133010&quot;,&quot;0.1.0-ci-20210208-235527&quot;,&quot;0.1.0-ci-20210210-215134&quot;,&quot;0.1.0-ci-20210211-180018&quot;,&quot;0.1.0-ci-20210220-123834&quot;,&quot;0.1.0-ci-20210220-161521&quot;,&quot;0.1.0-ci-20210223-083609&quot;,&quot;0.1.0-ci-20210227-122954&quot;,&quot;0.1.0-ci-20210227-145637&quot;,&quot;0.1.0-ci-20210227-145902&quot;,&quot;0.1.0-ci-20210304-203550&quot;,&quot;0.1.0-ci-20210807-163214&quot;,&quot;0.1.0-ci-20210808-105103&quot;,&quot;0.1.0-ci-20210808-110016&quot;,&quot;0.1.0-ci-20210808-114931&quot;,&quot;0.1.0-ci-20210808-141049&quot;,&quot;0.1.0-ci-20210808-223150 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slipeserver_scripting_versions_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.versions.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;tslib&quot;,&quot;_rev&quot;:&quot;78-cb398e6ce0b13d23a20af78cebd80bd9&quot;,&quot;name&quot;:&quot;tslib&quot;,&quot;time&quot;:{&quot;modified&quot;:&quot;2022-10-31T18:26:42.070Z&quot;,&quot;created&quot;:&quot;2014-12-30T09:21:20.138Z&quot;,&quot;0.0.1&quot;:&quot;2014-12-30T09:21:22.769Z&quot;,&quot;0.0.2&quot;:&quot;2014-12-30T11:02:46.195Z&quot;,&quot;0.0.1-security&quot;:&quot;2016-06-16T22:56:19.306Z&quot;,&quot;1.0.0&quot;:&quot;2016-06-28T00:46:05.835Z&quot;,&quot;1.1.0&quot;:&quot;2016-11-21T19:18:50.947Z&quot;,&quot;1.2.0&quot;:&quot;2016-11-30T01:20:12.477Z&quot;,&quot;1.3.0&quot;:&quot;2016-12-21T17:39:27.117Z&quot;,&quot;1.4.0&quot;:&quot;2016-12-22T04:46:12.098Z&quot;,&quot;1.5.0&quot;:&quot;2017-01-05T18:07:30.457Z&quot;,&quot;1.6.0&quot;:&quot;2017-02-22T00:24:40.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tslib_json {
            get {
                return ResourceManager.GetString("tslib.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@somosme/webflowutils&quot;,&quot;_rev&quot;:&quot;3-9be941baa0509bbc96a1349f8464fd6d&quot;,&quot;name&quot;:&quot;@somosme/webflowutils&quot;,&quot;time&quot;:{&quot;created&quot;:&quot;2022-08-10T19:49:56.913Z&quot;,&quot;1.0.0&quot;:&quot;2022-08-10T19:49:57.198Z&quot;,&quot;modified&quot;:&quot;2022-08-10T21:31:52.293Z&quot;,&quot;unpublished&quot;:{&quot;time&quot;:&quot;2022-08-10T21:31:32.856Z&quot;,&quot;versions&quot;:[&quot;1.0.0&quot;]}},&quot;maintainers&quot;:[{&quot;email&quot;:&quot;antonio@somos.me&quot;,&quot;name&quot;:&quot;antoniomb&quot;}]}.
        /// </summary>
        internal static string unpublishedpackage_json {
            get {
                return ResourceManager.GetString("unpublishedpackage.json", resourceCulture);
            }
        }
    }
}
