//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("oss-tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@achievementify/client&quot;,&quot;_rev&quot;:&quot;12-8838c4a3d8562d02f2daef2375606cf6&quot;,&quot;time&quot;:{&quot;created&quot;:&quot;2022-06-04T14:02:08.273Z&quot;,&quot;0.1.0&quot;:&quot;2022-06-04T13:57:49.506Z&quot;,&quot;modified&quot;:&quot;2022-06-07T01:29:39.806Z&quot;,&quot;0.1.1&quot;:&quot;2022-06-04T14:02:08.514Z&quot;,&quot;0.1.2&quot;:&quot;2022-06-04T14:05:49.363Z&quot;,&quot;0.1.3&quot;:&quot;2022-06-04T14:22:29.219Z&quot;,&quot;0.2.0&quot;:&quot;2022-06-05T13:10:17.513Z&quot;,&quot;0.2.1&quot;:&quot;2022-06-07T01:17:09.495Z&quot;,&quot;0.2.3&quot;:&quot;2022-06-07T01:29:39.737Z&quot;},&quot;name&quot;:&quot;@achievementify/client&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.2.3&quot;},&quot;versions&quot;:{&quot;0.1.1&quot;:{&quot;name&quot;:&quot;@achievementif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string achievementify_client_json {
            get {
                return ResourceManager.GetString("achievementify_client.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@angular/core&quot;,&quot;_rev&quot;:&quot;660-3fe4d5b1b9e632c7d96cdc1e1005b13c&quot;,&quot;name&quot;:&quot;@angular/core&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;13.2.6&quot;,&quot;v4-lts&quot;:&quot;4.4.7&quot;,&quot;v5-lts&quot;:&quot;5.2.11&quot;,&quot;next&quot;:&quot;13.3.0-rc.0&quot;,&quot;v7-lts&quot;:&quot;7.2.15&quot;,&quot;v6-lts&quot;:&quot;6.1.10&quot;,&quot;v9-lts&quot;:&quot;9.1.13&quot;,&quot;v8-lts&quot;:&quot;8.2.14&quot;,&quot;v10-lts&quot;:&quot;10.2.5&quot;,&quot;v11-lts&quot;:&quot;11.2.14&quot;,&quot;v12-lts&quot;:&quot;12.2.16&quot;},&quot;versions&quot;:{&quot;0.0.0-0&quot;:{&quot;name&quot;:&quot;@angular/core&quot;,&quot;version&quot;:&quot;0.0.0-0&quot;,&quot;description&quot;:&quot;&quot;,&quot;main&quot;:&quot;index.js&quot;,&quot;jsnext:main&quot;:&quot;esm/index.js&quot;,&quot;typings&quot;:&quot;index.d.ts&quot;,&quot;author&quot;:{&quot;name&quot;:&quot;angular&quot;},&quot;license&quot;:&quot;MIT&quot;,&quot;pee [rest of string was tru....
        /// </summary>
        internal static string angular_core_json {
            get {
                return ResourceManager.GetString("angular_core.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;rand&quot;,&quot;vers&quot;:&quot;0.1.1&quot;,&quot;deps&quot;:[],&quot;cksum&quot;:&quot;48a45b46c2a8c38348adb1205b13c3c5eb0174e0c0fec52cc88e9fb1de14c54d&quot;,&quot;features&quot;:{},&quot;yanked&quot;:false}
        ///{&quot;name&quot;:&quot;rand&quot;,&quot;vers&quot;:&quot;0.1.2&quot;,&quot;deps&quot;:[{&quot;name&quot;:&quot;libc&quot;,&quot;req&quot;:&quot;^0.1.1&quot;,&quot;features&quot;:[&quot;&quot;],&quot;optional&quot;:false,&quot;default_features&quot;:true,&quot;target&quot;:null,&quot;kind&quot;:&quot;normal&quot;},{&quot;name&quot;:&quot;log&quot;,&quot;req&quot;:&quot;^0.2.1&quot;,&quot;features&quot;:[&quot;&quot;],&quot;optional&quot;:false,&quot;default_features&quot;:true,&quot;target&quot;:null,&quot;kind&quot;:&quot;normal&quot;}],&quot;cksum&quot;:&quot;6e229ed392842fa93c1d76018d197b7e1b74250532bafb37b0e1d121a92d4cf7&quot;,&quot;features&quot;:{},&quot;ya [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cargo_rand {
            get {
                return ResourceManager.GetString("cargo.rand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;ds-modal&quot;,&quot;_rev&quot;:&quot;9-9ea35761f56735940a8303bde2186667&quot;,&quot;time&quot;:{&quot;1.0.0&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.1&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.2&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.3&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;1.0.4&quot;:&quot;2018-08-05T11:35:40.880Z&quot;,&quot;created&quot;:&quot;2018-08-06T12:04:34.792Z&quot;,&quot;0.0.0&quot;:&quot;2018-08-06T12:04:34.910Z&quot;,&quot;modified&quot;:&quot;2018-08-09T07:24:09.131Z&quot;,&quot;0.0.1&quot;:&quot;2018-08-09T04:53:46.623Z&quot;,&quot;0.0.2&quot;:&quot;2018-08-09T07:24:06.206Z&quot;},&quot;name&quot;:&quot;ds-modal&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.2&quot;},&quot;versions&quot;:{&quot;0.0.0&quot;:{&quot;name&quot;:&quot;ds-modal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ds_modal_json {
            get {
                return ResourceManager.GetString("ds-modal.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;lodash&quot;,&quot;_rev&quot;:&quot;2650-7b310ba0ce49a17115204773ce251b7f&quot;,&quot;name&quot;:&quot;lodash&quot;,&quot;description&quot;:&quot;Lodash modular utilities.&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;4.17.21&quot;},&quot;versions&quot;:{&quot;0.1.0&quot;:{&quot;name&quot;:&quot;lodash&quot;,&quot;version&quot;:&quot;0.1.0&quot;,&quot;description&quot;:&quot;A drop-in replacement for Underscore.js that delivers up to 8x performance improvements, bug fixes, and additional features.&quot;,&quot;homepage&quot;:&quot;https://github.com/bestiejs/lodash&quot;,&quot;main&quot;:&quot;lodash&quot;,&quot;keywords&quot;:[&quot;browser&quot;,&quot;client&quot;,&quot;functional&quot;,&quot;performance&quot;,&quot;server&quot;,&quot;speed&quot;,&quot;util&quot;],&quot;licenses&quot;:[{&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lodash_json {
            get {
                return ResourceManager.GetString("lodash.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;lodash.js&quot;,&quot;_rev&quot;:&quot;7-b033eedf4d1b14d686a8c537585bb116&quot;,&quot;time&quot;:{&quot;4.17.16&quot;:&quot;2019-11-25T16:45:29.666Z&quot;,&quot;created&quot;:&quot;2019-11-25T18:50:27.244Z&quot;,&quot;0.0.1-security&quot;:&quot;2019-11-25T18:50:27.445Z&quot;,&quot;modified&quot;:&quot;2022-05-08T08:11:30.890Z&quot;},&quot;name&quot;:&quot;lodash.js&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.1-security&quot;},&quot;versions&quot;:{&quot;0.0.1-security&quot;:{&quot;name&quot;:&quot;lodash.js&quot;,&quot;version&quot;:&quot;0.0.1-security&quot;,&quot;description&quot;:&quot;security holding package&quot;,&quot;repository&quot;:{&quot;type&quot;:&quot;git&quot;,&quot;url&quot;:&quot;git+https://github.com/npm/security-holder.git&quot;},&quot;gitHead&quot;:&quot;ac50be87aafecb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lodashjs_json {
            get {
                return ResourceManager.GetString("lodashjs.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;example&quot;,&quot;name&quot;:&quot;example&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.0&quot;},&quot;versions&quot;:{&quot;0.0.0&quot;:{&quot;name&quot;:&quot;example&quot;,&quot;version&quot;:&quot;0.0.0&quot;,&quot;_id&quot;:&quot;example@0.0.0&quot;,&quot;_npmVersion&quot;:&quot;1.0.0&quot;,&quot;_npmUser&quot;:{&quot;name&quot;:&quot;test&quot;,&quot;email&quot;:&quot;test@microsoft.com&quot;}}}}.
        /// </summary>
        internal static string minimum_json_json {
            get {
                return ResourceManager.GetString("minimum_json.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;monorepolint&quot;,&quot;_rev&quot;:&quot;87-5da61e286f7f5e22c777a521cea5ef96&quot;,&quot;name&quot;:&quot;monorepolint&quot;,&quot;dist-tags&quot;:{&quot;canary&quot;:&quot;0.5.0-alpha.81&quot;,&quot;latest&quot;:&quot;0.4.0&quot;},&quot;versions&quot;:{&quot;0.2.1-alpha.0&quot;:{&quot;name&quot;:&quot;monorepolint&quot;,&quot;version&quot;:&quot;0.2.1-alpha.0&quot;,&quot;license&quot;:&quot;MIT&quot;,&quot;scripts&quot;:{&quot;clean&quot;:&quot;rm -rf build lib&quot;,&quot;compile:typescript&quot;:&quot;../../node_modules/.bin/tsc&quot;,&quot;jest:watch&quot;:&quot;../../node_modules/.bin/jest --config ../../jest.config.js --watch&quot;,&quot;jest&quot;:&quot;../../node_modules/.bin/jest --config ../../jest.config.js&quot;,&quot;lint:typescript&quot;:&quot;../../node_modu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monorepolint_json {
            get {
                return ResourceManager.GetString("monorepolint.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:&quot;3.0.0&quot;,&quot;resources&quot;:[{&quot;@id&quot;:&quot;https://azuresearch-usnc.nuget.org/query&quot;,&quot;@type&quot;:&quot;SearchQueryService&quot;,&quot;comment&quot;:&quot;Query endpoint of NuGet Search service (primary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-ussc.nuget.org/query&quot;,&quot;@type&quot;:&quot;SearchQueryService&quot;,&quot;comment&quot;:&quot;Query endpoint of NuGet Search service (secondary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-usnc.nuget.org/autocomplete&quot;,&quot;@type&quot;:&quot;SearchAutocompleteService&quot;,&quot;comment&quot;:&quot;Autocomplete endpoint of NuGet Search service (primary)&quot;},{&quot;@id&quot;:&quot;https://azuresearch-ussc.n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nuget_registration_json {
            get {
                return ResourceManager.GetString("nuget_registration.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;The Pandas Development Team&quot;,&quot;author_email&quot;:&quot;pandas-dev@python.org&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Environment :: Console&quot;,&quot;Intended Audience :: Science/Research&quot;,&quot;License :: OSI Approved :: BSD License&quot;,&quot;Operating System :: OS Independent&quot;,&quot;Programming Language :: Cython&quot;,&quot;Programming Language :: Python&quot;,&quot;Programming Language :: Python :: 3&quot;,&quot;Programming Language :: Python :: 3 :: Only&quot;,&quot;Programming Language :: Python :: 3.8&quot;,&quot;Programmin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pandas_json {
            get {
                return ResourceManager.GetString("pandas.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;Chris P&quot;,&quot;author_email&quot;:&quot;chris@plot.ly&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Programming Language :: Python :: 3.6&quot;,&quot;Programming Language :: Python :: 3.7&quot;,&quot;Programming Language :: Python :: 3.8&quot;,&quot;Programming Language :: Python :: 3.9&quot;,&quot;Topic :: Scientific/Engineering :: Visualization&quot;],&quot;description&quot;:&quot;# plotly.py\n\n&lt;table&gt;\n    &lt;tr&gt;\n        &lt;td&gt;Latest Release&lt;/td&gt;\n        &lt;td&gt;\n            &lt;a href=\&quot;https://pypi.org/project/plotly/\&quot;/&gt;\n     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plotly_json {
            get {
                return ResourceManager.GetString("plotly.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2022.03.11.23.17.27/razorengine.4.2.3-beta1.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;c6bb0713-e534-4b16-8fdc-e199a77a6d73&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2022-03-11T23:17:27.9312336Z&quot;,
        ///  &quot;copyright&quot;: &quot;Copyright 2015&quot;,
        ///  &quot;created&quot;: &quot;2015-10-06T17:53:46.37Z&quot;,
        ///  &quot;description&quot;: &quot;RazorEngine - A Templating Engine based on the Razor parser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_4_2_3_beta1_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;authors&quot;:&quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,&quot;dependencyGroups&quot;:[{&quot;TargetFramework&quot;:{&quot;Framework&quot;:&quot;Any&quot;,&quot;Version&quot;:&quot;0.0.0.0&quot;,&quot;Platform&quot;:&quot;&quot;,&quot;PlatformVersion&quot;:&quot;0.0.0.0&quot;,&quot;HasPlatform&quot;:false,&quot;HasProfile&quot;:false,&quot;Profile&quot;:&quot;&quot;,&quot;DotNetFrameworkName&quot;:&quot;Any,Version=v0.0&quot;,&quot;DotNetPlatformName&quot;:&quot;&quot;,&quot;IsPCL&quot;:false,&quot;IsPackageBased&quot;:false,&quot;AllFrameworkVersions&quot;:true,&quot;IsUnsupported&quot;:false,&quot;IsAgnostic&quot;:false,&quot;IsAny&quot;:true,&quot;IsSpecificFramework&quot;:false},&quot;Packages&quot;:[{&quot;Id&quot;:&quot;Microsoft.AspNet.Razor&quot;,&quot;Include&quot;:[],&quot;Exclude&quot;:[] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_4_2_3_beta1_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.metadata.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/razorengine/index.json&quot;,&quot;@type&quot;:[&quot;catalog:CatalogRoot&quot;,&quot;PackageRegistration&quot;,&quot;catalog:Permalink&quot;],&quot;commitId&quot;:&quot;b44e2827-f5db-4ba2-bb8c-5e538ad0e7b1&quot;,&quot;commitTimeStamp&quot;:&quot;2022-03-11T23:18:21.9196828+00:00&quot;,&quot;count&quot;:2,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration5-gz-semver2/razorengine/index.json#page/2.1.0/4.1.5-beta1&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;b44e2827-f5db-4ba2-bb8c-5e538ad0e7b1&quot;,&quot;commitTimeStamp&quot;:&quot;2022-03-11T23:18:21.9196828+0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_json {
            get {
                return ResourceManager.GetString("razorengine.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;authors&quot;:&quot;Matthew Abbott, Ben Dornis, Matthias Dittrich&quot;,&quot;dependencyGroups&quot;:[{&quot;TargetFramework&quot;:{&quot;Framework&quot;:&quot;.NETFramework&quot;,&quot;Version&quot;:&quot;4.5.1.0&quot;,&quot;Platform&quot;:&quot;&quot;,&quot;PlatformVersion&quot;:&quot;0.0.0.0&quot;,&quot;HasPlatform&quot;:false,&quot;HasProfile&quot;:false,&quot;Profile&quot;:&quot;&quot;,&quot;DotNetFrameworkName&quot;:&quot;.NETFramework,Version=v4.5.1&quot;,&quot;DotNetPlatformName&quot;:&quot;&quot;,&quot;IsPCL&quot;:false,&quot;IsPackageBased&quot;:false,&quot;AllFrameworkVersions&quot;:false,&quot;IsUnsupported&quot;:false,&quot;IsAgnostic&quot;:false,&quot;IsAny&quot;:false,&quot;IsSpecificFramework&quot;:true},&quot;Packages&quot;:[{&quot;Id&quot;:&quot;Microsoft.AspNetCore.Razor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string razorengine_latest_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.latest.metadata.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;2.1.0&quot;,&quot;3.0.0&quot;,&quot;3.0.3&quot;,&quot;3.0.4&quot;,&quot;3.0.5&quot;,&quot;3.0.6&quot;,&quot;3.0.7&quot;,&quot;3.0.8&quot;,&quot;3.1.0&quot;,&quot;3.2.0&quot;,&quot;3.3.0&quot;,&quot;3.4.0&quot;,&quot;3.4.1&quot;,&quot;3.4.2&quot;,&quot;3.5.0-beta1&quot;,&quot;3.5.0-beta2&quot;,&quot;3.5.0-beta3&quot;,&quot;3.5.0&quot;,&quot;3.5.1&quot;,&quot;3.5.2&quot;,&quot;3.5.3&quot;,&quot;3.6.0&quot;,&quot;3.6.1&quot;,&quot;3.6.2&quot;,&quot;3.6.3-beta1&quot;,&quot;3.6.3-beta2&quot;,&quot;3.6.3&quot;,&quot;3.6.4&quot;,&quot;3.6.5-beta1&quot;,&quot;3.6.5&quot;,&quot;3.6.6-beta1&quot;,&quot;3.6.6-beta2&quot;,&quot;3.6.6&quot;,&quot;3.7.0-beta1&quot;,&quot;3.7.0&quot;,&quot;3.7.1-alpha1&quot;,&quot;3.7.2&quot;,&quot;3.7.3&quot;,&quot;3.7.4&quot;,&quot;3.7.5-beta1&quot;,&quot;3.7.5-beta2&quot;,&quot;3.7.5&quot;,&quot;3.7.6&quot;,&quot;3.7.7&quot;,&quot;3.8.0&quot;,&quot;3.8.1&quot;,&quot;3.8.2&quot;,&quot;3.9.0&quot;,&quot;3.9.1&quot;,&quot;3.9.2&quot;,&quot;3.9.3&quot;,&quot;3.10.0&quot;,&quot;3.10....
        /// </summary>
        internal static string razorengine_versions_json {
            get {
                return ResourceManager.GetString("razorengine.versions.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{&quot;author&quot;:&quot;Kenneth Reitz&quot;,&quot;author_email&quot;:&quot;me@kennethreitz.org&quot;,&quot;bugtrack_url&quot;:null,&quot;classifiers&quot;:[&quot;Development Status :: 5 - Production/Stable&quot;,&quot;Environment :: Web Environment&quot;,&quot;Intended Audience :: Developers&quot;,&quot;License :: OSI Approved :: Apache Software License&quot;,&quot;Natural Language :: English&quot;,&quot;Operating System :: OS Independent&quot;,&quot;Programming Language :: Python&quot;,&quot;Programming Language :: Python :: 2&quot;,&quot;Programming Language :: Python :: 2.7&quot;,&quot;Programming Language :: Python :: 3&quot;,&quot;Programming Language :: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string requests_json {
            get {
                return ResourceManager.GetString("requests.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;rly-cli&quot;,&quot;_rev&quot;:&quot;3-25e14d2a4e035503eb10824c39a04e6c&quot;,&quot;name&quot;:&quot;rly-cli&quot;,&quot;dist-tags&quot;:{&quot;latest&quot;:&quot;0.0.4&quot;},&quot;versions&quot;:{&quot;0.0.1&quot;:{&quot;name&quot;:&quot;rly-cli&quot;,&quot;version&quot;:&quot;0.0.1&quot;,&quot;description&quot;:&quot;DFS CLI allows you to setup fungilble SPL tokens and call Rally token programs from the command line.&quot;,&quot;bin&quot;:{&quot;rly-cli&quot;:&quot;lib/cli/src/rly-cli.js&quot;},&quot;keywords&quot;:[],&quot;author&quot;:&quot;&quot;,&quot;scripts&quot;:{&quot;tsc&quot;:&quot;tsc&quot;,&quot;test&quot;:&quot;./node_modules/ts-mocha/bin/ts-mocha -p ./tsconfig.json -t 1000000 -r dotenv/config tests/**/*.ts&quot;},&quot;license&quot;:&quot;ISC&quot;,&quot;publishConfi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rly_cli_json {
            get {
                return ResourceManager.GetString("rly-cli.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_id&quot;:&quot;@somosme/webflowutils&quot;,&quot;_rev&quot;:&quot;3-9be941baa0509bbc96a1349f8464fd6d&quot;,&quot;name&quot;:&quot;@somosme/webflowutils&quot;,&quot;time&quot;:{&quot;created&quot;:&quot;2022-08-10T19:49:56.913Z&quot;,&quot;1.0.0&quot;:&quot;2022-08-10T19:49:57.198Z&quot;,&quot;modified&quot;:&quot;2022-08-10T21:31:52.293Z&quot;,&quot;unpublished&quot;:{&quot;time&quot;:&quot;2022-08-10T21:31:32.856Z&quot;,&quot;versions&quot;:[&quot;1.0.0&quot;]}},&quot;maintainers&quot;:[{&quot;email&quot;:&quot;antonio@somos.me&quot;,&quot;name&quot;:&quot;antoniomb&quot;}]}.
        /// </summary>
        internal static string unpublishedpackage_json {
            get {
                return ResourceManager.GetString("unpublishedpackage.json", resourceCulture);
            }
        }
    }
}
