//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oss {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("oss-tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string angular_core_json {
            get {
                return ResourceManager.GetString("angular_core.json", resourceCulture);
            }
        }
        
        internal static string achievementify_client_json {
            get {
                return ResourceManager.GetString("achievementify_client.json", resourceCulture);
            }
        }
        
        internal static string ds_modal_json {
            get {
                return ResourceManager.GetString("ds-modal.json", resourceCulture);
            }
        }
        
        internal static string lodash_json {
            get {
                return ResourceManager.GetString("lodash.json", resourceCulture);
            }
        }
        
        internal static string lodashjs_json {
            get {
                return ResourceManager.GetString("lodashjs.json", resourceCulture);
            }
        }
        
        internal static string monorepolint_json {
            get {
                return ResourceManager.GetString("monorepolint.json", resourceCulture);
            }
        }
        
        internal static string rly_cli_json {
            get {
                return ResourceManager.GetString("rly-cli.json", resourceCulture);
            }
        }
        
        internal static string minimum_json_json {
            get {
                return ResourceManager.GetString("minimum_json.json", resourceCulture);
            }
        }
        
        internal static string tslib_json {
            get {
                return ResourceManager.GetString("tslib.json", resourceCulture);
            }
        }
        
        internal static string unpublishedpackage_json {
            get {
                return ResourceManager.GetString("unpublishedpackage.json", resourceCulture);
            }
        }
        
        internal static string razorengine_json {
            get {
                return ResourceManager.GetString("razorengine.json", resourceCulture);
            }
        }
        
        internal static string razorengine_latest_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.latest.metadata.json", resourceCulture);
            }
        }
        
        internal static string razorengine_versions_json {
            get {
                return ResourceManager.GetString("razorengine.versions.json", resourceCulture);
            }
        }
        
        internal static string razorengine_4_2_3_beta1_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.json", resourceCulture);
            }
        }
        
        internal static string razorengine_4_2_3_beta1_metadata_json {
            get {
                return ResourceManager.GetString("razorengine.4.2.3-beta1.metadata.json", resourceCulture);
            }
        }
        
        internal static string slipeserver_scripting_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.json", resourceCulture);
            }
        }
        
        internal static string slipeserver_scripting_versions_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.versions.json", resourceCulture);
            }
        }
        
        internal static string slipeserver_scripting_catalogpage_2_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.catalogpage.2.json", resourceCulture);
            }
        }
        
        internal static string slipeserver_scripting_catalogpage_3_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.catalogpage.3.json", resourceCulture);
            }
        }
        
        internal static string slipeserver_scripting_0_1_0_ci_20220607_083949_json {
            get {
                return ResourceManager.GetString("slipeserver.scripting.0.1.0-ci-20220607-083949.json", resourceCulture);
            }
        }
        
        internal static string nuget_registration_json {
            get {
                return ResourceManager.GetString("nuget_registration.json", resourceCulture);
            }
        }
        
        internal static string pandas_json {
            get {
                return ResourceManager.GetString("pandas.json", resourceCulture);
            }
        }
        
        internal static string plotly_json {
            get {
                return ResourceManager.GetString("plotly.json", resourceCulture);
            }
        }
        
        internal static string requests_json {
            get {
                return ResourceManager.GetString("requests.json", resourceCulture);
            }
        }
        
        internal static string pandas_1_4_2_json {
            get {
                return ResourceManager.GetString("pandas_1.4.2.json", resourceCulture);
            }
        }
        
        internal static string plotly_5_7_0_json {
            get {
                return ResourceManager.GetString("plotly_5.7.0.json", resourceCulture);
            }
        }
        
        internal static string requests_2_27_1_json {
            get {
                return ResourceManager.GetString("requests_2.27.1.json", resourceCulture);
            }
        }
        
        internal static string cargo_rand {
            get {
                return ResourceManager.GetString("cargo.rand", resourceCulture);
            }
        }
        
        internal static string cargo_rand_json {
            get {
                return ResourceManager.GetString("cargo.rand.json", resourceCulture);
            }
        }
        
        internal static string maven_ant_1_6_html {
            get {
                return ResourceManager.GetString("maven_ant_1.6_html", resourceCulture);
            }
        }
        
        internal static string maven_ant_all_html {
            get {
                return ResourceManager.GetString("maven_ant_all_html", resourceCulture);
            }
        }
        
        internal static string maven_ant_metadata_xml {
            get {
                return ResourceManager.GetString("maven_ant_metadata_xml", resourceCulture);
            }
        }
        
        internal static string maven_ant_1_6_pom {
            get {
                return ResourceManager.GetString("maven_ant_1.6_pom", resourceCulture);
            }
        }
        
        internal static string maven_microsoft_fluentui_listitem_0_0_8_html {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_0.0.8_html", resourceCulture);
            }
        }
        
        internal static string maven_microsoft_fluentui_listitem_all_html {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_all_html", resourceCulture);
            }
        }
        
        internal static string maven_microsoft_fluentui_listitem_metadata_xml {
            get {
                return ResourceManager.GetString("maven_microsoft_fluentui_listitem_metadata_xml", resourceCulture);
            }
        }
        
        internal static string maven_fluentui_listitem_0_0_8_pom {
            get {
                return ResourceManager.GetString("maven_fluentui_listitem_0.0.8_pom", resourceCulture);
            }
        }
        
        internal static string go_yaml_list {
            get {
                return ResourceManager.GetString("go_yaml_list", resourceCulture);
            }
        }
        
        internal static string go_yaml_1_3_0_info {
            get {
                return ResourceManager.GetString("go_yaml_1.3.0_info", resourceCulture);
            }
        }
        
        internal static string go_yaml_1_3_0_mod {
            get {
                return ResourceManager.GetString("go_yaml_1.3.0_mod", resourceCulture);
            }
        }
        
        internal static string jdalton_packages_json {
            get {
                return ResourceManager.GetString("jdalton_packages.json", resourceCulture);
            }
        }
        
        internal static string microsoft_packages_json {
            get {
                return ResourceManager.GetString("microsoft_packages.json", resourceCulture);
            }
        }
        
        internal static string azure_packages_json {
            get {
                return ResourceManager.GetString("azure_packages.json", resourceCulture);
            }
        }
        
        internal static string microsoft_pypi_profile_html {
            get {
                return ResourceManager.GetString("microsoft_pypi_profile.html", resourceCulture);
            }
        }
    }
}
