// Copyright (c) Microsoft Corporation. Licensed under the MIT License.

namespace Microsoft.CST.OpenSource.FindSquats
{
    using CommandLine;
    using CommandLine.Text;
    using Microsoft.CodeAnalysis.Sarif;
    using Microsoft.CST.OpenSource.Shared;
    using Mutators;
    using Newtonsoft.Json;
    using OssGadget.Options;
    using PackageManagers;
    using PackageUrl;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading.Tasks;
    using SarifResult = Microsoft.CodeAnalysis.Sarif.Result;

    public class FindSquatsTool : BaseTool<FindSquatsToolOptions>
    {
        public FindSquatsTool(ProjectManagerFactory projectManagerFactory) : base(projectManagerFactory)
        {
        }

        public FindSquatsTool() : this(new ProjectManagerFactory())
        {
        }

        public override async Task<ErrorCode> RunAsync(FindSquatsToolOptions options)
        { 
            (string output, int numSquats) = (string.Empty, 0);
            (output, numSquats) = await LegacyRunAsync(options);
            if (string.IsNullOrEmpty(options.OutputFile))
            {
                options.OutputFile = $"oss-find-squat.{options.Format}";
            }
            if (!options.Quiet)
            {
                if (numSquats > 0)
                {
                    Logger.Warn($"Found {numSquats} potential squats.");
                }
                else
                {
                    Logger.Info($"No squats detected.");
                }
            }
            using StreamWriter fw = new(options.OutputFile);
            await fw.WriteLineAsync(output);
            fw.Close();
            return ErrorCode.Ok;
        }

        public async Task<(string output, int numSquats)> LegacyRunAsync(FindSquatsToolOptions options)
        {
            IOutputBuilder? outputBuilder = SelectFormat(options.Format);
            int foundSquats = 0;
            MutateOptions? checkerOptions = new()
            {
                SleepDelay = options.SleepDelay
            };
            foreach (string? target in options.Targets ?? Array.Empty<string>())
            {
                PackageURL? purl = new(target);
                if (purl.Name is null || purl.Type is null)
                {
                    Logger.Trace($"Could not generate valid PackageURL from { target }.");
                    continue;
                }

                FindPackageSquats findPackageSquats = new FindPackageSquats(ProjectManagerFactory, purl);

                IDictionary<string, IList<Mutation>>? potentialSquats = findPackageSquats.GenerateSquatCandidates(options: checkerOptions);

                await foreach (FindPackageSquatResult? potentialSquat in findPackageSquats.FindExistingSquatsAsync(potentialSquats, checkerOptions))
                {
                    foundSquats++;
                    if (!options.Quiet)
                    {
                        Logger.Info($"{potentialSquat.MutatedPackageName} package exists. Potential squat. {JsonConvert.SerializeObject(potentialSquat.Rules)}");
                    }
                    if (outputBuilder is SarifOutputBuilder sarob)
                    {
                        SarifResult? sarifResult = new()
                        {
                            Message = new Message()
                            {
                                Text = $"Potential Squat candidate { potentialSquat.MutatedPackageName }.",
                                Id = "oss-find-squats"
                            },
                            Kind = ResultKind.Review,
                            Level = FailureLevel.None,
                            Locations = SarifOutputBuilder.BuildPurlLocation(potentialSquat.MutatedPackageUrl),
                        };
                        foreach (string? tag in potentialSquat.Rules)
                        {
                            sarifResult.Tags.Add(tag);
                        }
                        sarob.AppendOutput(new SarifResult[] { sarifResult });
                    }
                    else if (outputBuilder is StringOutputBuilder strob)
                    {
                        string? rulesString = string.Join(',', potentialSquat.Rules);
                        strob.AppendOutput(new string[] { $"Potential Squat candidate '{ potentialSquat.MutatedPackageName }' detected. Generated by { rulesString }.{Environment.NewLine}" });
                    }
                    else
                    {
                        string? rulesString = string.Join(',', potentialSquat.Rules);
                        if (!options.Quiet)
                        {
                            Logger.Info($"Potential Squat candidate '{ potentialSquat.MutatedPackageName }' detected. Generated by { rulesString }.");
                        }
                    }
                }
            }

            return (outputBuilder.GetOutput(), foundSquats);
        }
    }
}
