parameters:
# Job Name
- name: jobName
  type: string
  default: 'check_changes'
# tag name
- name: tagName
  type: string
  default: 'code_changed'
# Comma Separated paths Name
- name: pathArgument
  type: string
  default: '/'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Checking for changed paths
  steps:
    - bash: |
        CHANGED_FILES=$(git diff HEAD HEAD~ --name-only)
        echo "Checking for file changes..."

        readarray -d , -t strarr <<<"${{ parameters.pathArgument }}"  

        for (( n=0; n < ${#strarr[*]} && !DONE; n++ ))  
        do  
          for FILE in $CHANGED_FILES
          do
            if [[ $FILE == *${strarr[n]}* ]]; then
              echo "MATCH:  ${FILE} changed"
              echo "##vso[task.setvariable variable=${{ parameters.tagName }};isOutput=true]true"
              DONE=true
              break
            fi
          done
        done

        if [ -z ${DONE} ]; then
          echo "No matching paths found."
          echo "##vso[task.setvariable variable=${{ parameters.tagName }};isOutput=true]false"
        fi

        echo $${{parameters.tagName}}
      name: check_script
