parameters:
# Job Name
- name: jobName
  type: string
  default: 'dotnet_test'
# Version of Dotnet SDK to use
- name: dotnetVersion
  type: string
  default: '6.0.x'
# Should Dotnet SDK install preview versions?
- name: includePreviewVersions
  type: boolean
  default: false
# List of paths to .csproj
- name: projectPath
  type: string
  default: ''
# Additional 'dotnet test' arguments
- name: arguments
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: Dotnet Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: Install Dotnet SDK
    inputs:
      packageType: 'sdk'
      version: ${{ parameters.dotnetVersion }}
      includePreviewVersions: ${{ parameters.includePreviewVersions }}
  - task: DotNetCoreCLI@2
    displayName: Dotnet Restore
    inputs:
      command: 'restore'
      projects: ${{ parameters.projectPath }}
      verbosityRestore: 'Normal'
  - task: DotNetCoreCLI@2
    displayName: Dotnet Test
    inputs:
      command: 'test'
      projects: ${{ parameters.projectPath }}
      arguments: ${{ parameters.arguments }}