name: OSSGadget_PR_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    stages:
    - stage: Build
      jobs:
      - job: Build
#        templateContext:
#          outputs:
#          - output: pipelineArtifact
#            path: $(Build.SourcesDirectory)/src/oss-gadget-cli/bin/$(buildConfiguration)
#            artifact: 'build_$(System.JobId)_$(System.JobAttempt)'

        steps:
        - task: UseDotNet@2
          displayName: Install Dotnet SDK
          inputs:
            packageType: 'sdk'
            version: $(dotnetVersion)

        - task: NuGetAuthenticate@1
        - task: NuGetCommand@2
          inputs:
            command: restore
            restoreSolution: '**/*.csproj'
            feedsToUse: config
            nugetConfigPath: 'nuget.config.azure'
            includeNuGetOrg: false

        - script: dir
          workingDirectory: '$(Build.SourcesDirectory)/src'
          displayName: List contents of a folder

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            displayName: 'dotnet build'
            workingDirectory: '$(Build.SourcesDirectory)/src'
            includeNuGetOrg: false
            arguments: >
              --configuration $(buildConfiguration)
              --framework $(dotnetVersion)
              --no-restore
              --configfile $(Build.SourcesDirectory)/nuget.config.azure

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            workingDirectory: $(Build.SourcesDirectory)
            projects: '**/Shared.Lib.Tests.csproj'
            arguments: > 
              --configuration $(buildConfiguration)
              -p:RestoreConfigFile=$(Build.SourcesDirectory)/nuget.config.azure
              --no-restore
              --no-build
