name: OSSGadget_PR_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  nugetConfig: '$(Build.SourcesDirectory)/nuget.config.azure'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    settings:
      networkIsolationPolicy: Permissive,CFSClean
    stages:
    - stage: Build
      jobs:
      - job: Build
        steps:
        - task: UseDotNet@2
          displayName: Install Dotnet SDK
          inputs:
            packageType: 'sdk'
            version: $(dotnetVersion)

        - task: NuGetAuthenticate@1
        - task: NuGetCommand@2
          inputs:
            command: restore
            restoreSolution: '**/*.sln'
            feedsToUse: config
            nugetConfigPath: $(nugetConfig)
            includeNuGetOrg: false

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            displayName: 'dotnet build'
            workingDirectory: '$(Build.SourcesDirectory)/src'
            arguments: >
              OssGadget.sln
              --configuration $(buildConfiguration)
              --no-restore
              --configfile $(nugetConfig)              

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '**/Shared.Lib.Tests.csproj'
            arguments: > 
              --configuration $(buildConfiguration)
              -p:RestoreConfigFile=$(nugetConfig)
              --no-restore
              --no-build
              --verbosity Diagnostic
