name: "EditorConfig Linting"

on:
  push:
    paths:
    - src/*
  pull_request:
    paths: 
    - src/*

jobs:
  Lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: EditorConfig-Action
      uses: zbeekman/EditorConfig-Action@v1.1.1
