trigger:
  tags:
    include: 
    - v0.*
  paths:
    include:
    - Pipelines/nuget-pipelines/oss-risk-calculator.yml
    - src/oss-risk-calculator
    - src/Shared

stages:
- stage: Release
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  jobs:
    - template: templates/nuget-build-job.yml
      parameters:
        jobName: 'pack oss-risk-calculator'
        projectPath: 'oss-risk-calculator/oss-risk-calculator.csproj'
        projectName: 'oss-risk-calculator'
    - task: PublishPipelineArtifact@1
      displayName: Publish Signed Artifacts to Pipeline
      inputs:
        targetPath: 'Packages'
        artifact: 'oss-risk-calculator Nuget'
    - task: NuGetCommand@2
      displayName: Push NuGet Packages
      inputs:
        command: 'push'
        packagesToPush: 'Packages/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'CST-E Nuget CI'
        verbosityPush: 'Normal'
