pr: none
trigger:
  tags:
    include: 
    - v0.*
  paths:
    include:
    - Pipelines
    - src/oss-find-squats
    - src/Shared

jobs:
- template: ../templates/nuget-build-job.yml
  parameters:
    jobName: 'pack_oss_find_squats'
    projectPath: 'src/oss-find-squats/oss-find-squats.csproj'
    projectName: 'oss-find-squats'
    publishToNuget: true