pr: none
trigger:
  tags:
    include: 
    - v0.*
  paths:
    include:
    - Pipelines
    - src/oss-find-squats
    - src/Shared

jobs:
- template: ../templates/nuget-build-job.yml
  parameters:
    jobName: 'pack_oss_find_squats'
    projectPath: 'src/oss-find-squats/oss-find-squats.csproj'
    projectName: 'oss-find-squats'
- job: Release_oss_find_squats
  dependsOn: pack_oss_find_squats
  displayName: Publish oss-find-squats nuget
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PublishPipelineArtifact@1
    displayName: Publish Signed Artifacts to Pipeline
    inputs:
      targetPath: 'Packages'
      artifact: 'OSS-Find-Squats Nuget'
  - task: NuGetCommand@2
    displayName: Push NuGet Packages
    inputs:
      command: 'push'
      packagesToPush: 'Packages/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'CST-E Nuget CI'
      verbosityPush: 'Normal'